// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqgoeplmilswiymuplev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxZ29lcGxtaWxzd2l5bXVwbGV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzY1MzYsImV4cCI6MjA2ODM1MjUzNn0.LekUt0qoHXE9IwYXwptrrCpdB987VmJeCM4yXmpv_uI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});